name: Deploy

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run Rspec
        run: bundle exec rspec

      - name: Run Cucumber
        run: bundle exec cucumber

  deploy:
    name: Deploy to dokku
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@dokku.wells.tw:22/ntust-senior'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_push_flags: --force -vvv

      - name: Run database migration
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: dokku.wells.tw
          username: dokku
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: run ntust-senior rails db:migrate
